### ISSUE TITLE
swift 3.0

### ISSUE THREAD

**Issue by ibrahimuslu** [HarryGoodwin/BLE_Scanner_iOS#2]
it gives an error after migrates to swift 3.0 then change the right side as below
	`	if (central.state == .poweredOn ){`

**Comment by ibrahimuslu** [comment]
This is the only working example of ble scanner app in my trials. ( OpenBLE, BluetoothKit and among others) Thank you for your effort

**Comment by HarryGoodwin** [comment]
Upgraded to Swift 3
